version: "3.8"

services:
  nevent-server:
    image: vicn1708/nevent-server
    container_name: nevent-server
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - mongodb
    networks:
      - nevent_network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: neventAdmin
      MONGO_INITDB_ROOT_PASSWORD: neventAdmin
    command: [--auth]
  networks:
    - nevent_network

  nevent-admin:
    image: vicn1708/nevent-admin
    container_name: nevent-admin
    restart: always
    ports:
      - "5000:5000"
    networks:
      - nevent_network

  nevent-client:
    image: vicn1708/nevent-client
    container_name: nevent-client
    restart: always
    ports:
      - "8080:8080"
    networks:
      - nevent_network

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certbot/letsencrypt:/etc/letsencrypt
      - ./nginx/cerbot/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/dhparam:/etc/ssl/certs
    depends_on:
      - nevent-client
      - nevent-admin
      - nevent-server
      - certbot
    networks:
      - nevent_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/cerbot/letsencrypt:/etc/letsencrypt
      - ./nginx/cerbot/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - webserver
    networks:
      - nevent_network
    # command: certonly --webroot --webroot-path /var/www/certbot/ --email vicn1708@gmail.com --agree-tos --no-eff-email --staging -d nevent.io.vn -d www.nevent.io.vn -d admin.nevent.io.vn -d www.admin.nevent.io.vn -d server.nevent.io.vn -d www.server.nevent.io.vn

networks:
  nevent_network:
    driver: bridge
